DoubleGis\TestBundle\Entity\Building:
  exclusion_policy: ALL
  properties:
    address:
      expose: true
  relations:
      - rel: organizations
        embedded:
            content: expr(object.getOrganizations())